export type Difficulty = "Easy" | "Medium" | "Hard";
export type Topic = { id: string; category: string; subject: string; text: string; difficulty: Difficulty };
export const categories = [
  { name: "Everyday life", icon: "☕", subjects: `the perfect slow morning|a small kindness you still remember|a hobby everyone should try|your most useful everyday object|the joy of doing nothing|why people keep things they never use|the unwritten rules of elevators|whether convenience makes us impatient|why we romanticize the past|how a neighborhood becomes a community|whether routines create freedom or limit it|the hidden cost of always being available|who gets to define a successful life|the trade-off between privacy and belonging|whether a simple life is a privilege` },
  { name: "Tech & AI", icon: "⌘", subjects: `an app you wish existed|a day without your phone|the most underrated invention|the gadget you would uninvent|what your search history says about you|whether AI can be a good friend|smart homes that outsmart their owners|the right age for a first smartphone|whether algorithms shape our taste|the future of passwords|who owns art made by AI|the right to disappear from the internet|whether software should have an expiry date|human accountability for autonomous decisions|whether digital memories should be editable` },
  { name: "Money & business", icon: "◈", subjects: `your best purchase under ten dollars|a business you could start tomorrow|what you would do with an unexpected bonus|a skill worth paying to learn|the appeal of a neighborhood shop|why subscriptions are everywhere|whether cash makes spending feel different|the value of a four-day workweek|whether tipping should exist|turning a hobby into a business|whether unlimited growth is a sensible goal|who pays for free online services|the ethics of personalized pricing|whether companies should publish every salary|the difference between creating value and capturing it` },
  { name: "Food & culture", icon: "♨", subjects: `a meal that tastes like home|the most overrated snack|the perfect midnight food|a food combination that deserves a chance|the ritual of making tea|why recipes change across generations|whether food can belong to one country|the case for eating alone|what restaurant menus reveal about us|whether cooking should be taught in school|the line between appreciation and appropriation in food|who should preserve disappearing cuisines|whether lab-grown food changes our relationship with nature|the ethics of culinary tourism|how convenience food reshapes family life` },
  { name: "Travel & adventure", icon: "✈", subjects: `a place you would revisit forever|your ideal train journey|a useful lesson from getting lost|what you always overpack|a holiday in your own city|whether travel needs a purpose|the appeal of traveling alone|how maps change the way we explore|whether famous landmarks are worth the queue|the best way to be a considerate visitor|whether travel makes people more open-minded|who a city belongs to during tourist season|the ethics of visiting fragile environments|whether borders limit imagination|the balance between sharing and protecting secret places` },
  { name: "Work & leadership", icon: "▣", subjects: `the best teammate you have had|a meeting that could have been a message|your first day at a new job|a skill your résumé cannot show|what makes feedback useful|whether great leaders need charisma|the difference between being busy and productive|how to disagree with your boss|what a good apology at work looks like|whether every passion needs a career|who benefits from the idea of professionalism|whether managers should be elected|the limits of measuring knowledge work|how to reward invisible labor|the tension between loyalty and speaking up` },
  { name: "Science & space", icon: "✦", subjects: `the animal superpower you would borrow|what you would take to the Moon|a science fact that changed your perspective|the invention of the wheel|why the night sky makes us curious|whether ocean exploration deserves more attention|what humans could learn from fungi|how to explain a black hole with household objects|the value of experiments that fail|whether we should bring back extinct species|who should own resources in space|how to communicate scientific uncertainty|whether every discovery should be published|the ethics of contacting extraterrestrial life|how civilization should plan for very distant risks` },
  { name: "Nature & climate", icon: "❋", subjects: `your favorite sound in nature|a tree with a story to tell|the value of a tiny garden|an animal you think is misunderstood|a day with no plastic|whether cities should have fewer lawns|the case for repairing things|why ugly animals need protection too|whether individual climate actions matter|the future of community gardens|whether nature should have legal rights|who should pay to adapt cities to heat|the fairness of carbon offsets|balancing conservation with local livelihoods|whether a river can be represented in a democracy` },
  { name: "Mind & habits", icon: "◎", subjects: `a habit that improved your day|the art of saying no|a fear you would like to overcome|what helps you focus|a lesson you learned the hard way|why we procrastinate on things we care about|whether boredom is useful|the difference between confidence and certainty|how social comparison changes ambition|whether motivation is overrated|whether a perfect memory would be a gift|how much of identity is a story we tell|the limits of optimizing every moment|whether happiness should be measured|the trade-off between comfort and personal growth` },
  { name: "Art & creativity", icon: "✎", subjects: `a song that instantly changes your mood|the book you would give a stranger|an unusual use for a paper clip|the movie ending you would rewrite|the beauty of a messy sketchbook|whether constraints make us more creative|why people love terrible movies|whether creative work needs an audience|the difference between inspiration and imitation|why handmade things feel different|whether art needs an artist's intention|who decides what belongs in a museum|whether a copy can be more meaningful than an original|the effect of patronage on creative freedom|whether art should comfort or disturb` },
  { name: "Relationships", icon: "♡", subjects: `what makes someone easy to talk to|a friendship built around a shared hobby|the best question to ask a new friend|a family tradition you would invent|a meaningful way to say thank you|whether friendship needs regular contact|the value of uncomfortable conversations|how to give advice without taking over|whether honesty always needs to be immediate|the difference between helping and rescuing|whether forgiveness requires reconciliation|the role of obligation in chosen families|when loyalty becomes a limitation|the ethics of sharing someone else's story|whether empathy can exist without shared experience` },
  { name: "Sports & games", icon: "⚑", subjects: `a sport you would invent|what board games teach us|your ideal playground game|the joy of being a beginner|a rule you would change in your favorite sport|whether losing builds character|why people support teams they have never seen|whether esports belong at the Olympics|the value of playing without keeping score|whether talent is overrated|the line between enhancement and unfair advantage|whether public money should fund stadiums|who owns a sporting tradition|the ethics of national allegiance in sport|whether perfect refereeing would improve the game` },
  { name: "Education", icon: "▤", subjects: `a subject missing from school|the teacher who made something click|a skill you learned outside a classroom|your ideal school lunch break|what children can teach adults|whether homework is useful|the case for teaching failure|whether students should grade teachers|the difference between knowing and understanding|why curiosity fades in classrooms|whether credentials are a fair measure of ability|who should decide what counts as essential knowledge|the tension between standardization and individuality|whether AI changes the meaning of assessment|what society owes lifelong learners` },
  { name: "Society & ethics", icon: "⚖", subjects: `a rule that makes everyday life better|a small way to improve your street|what makes a fair queue|an everyday act of courage|the importance of public benches|whether good intentions are enough|the difference between equality and fairness|whether anonymity makes people more honest|when breaking a rule is the right choice|the value of public libraries|whether future generations can have rights today|how to distribute a resource nobody created|whether justice always requires punishment|the limits of majority rule|whether moral progress can be measured` },
  { name: "Wild hypotheticals", icon: "✧", subjects: `a world where cats run the government|a complaint letter from your alarm clock|your first day as a friendly ghost|a supermarket for superheroes|a dragon applying for a desk job|a city where everyone can hear your thoughts|a world where sleep is a tradable currency|a society that votes on the weather|a phone that only receives messages from tomorrow|a planet with a ten-minute year|a world where lies change the speaker's appearance|a civilization that cannot forget anything|a market where people trade years of life|a democracy that includes trees|a society where everyone knows their exact future` },
  { name: "Gen Z & internet", icon: "↗", subjects: `a meme that deserves a museum|the perfect group chat name|a trend you happily skipped|your most irrational app notification|what your playlist reveals about you|whether everything needs a personal brand|the lifecycle of an internet joke|why people watch strangers do ordinary things|the difference between community and followers|whether going offline is a status symbol|how algorithms influence collective memory|the economics of being relatable online|whether virality rewards originality|who should inherit a digital identity|the tension between authenticity and performance` },
  { name: "Millennial nostalgia", icon: "▧", subjects: `the magic of a mixtape|a childhood gadget worth bringing back|the soundtrack to a school bus ride|the thrill of renting a movie|a snack from your childhood|whether the early internet felt more social|what we lost when photographs became unlimited|the appeal of owning music|why every generation misses its childhood|whether adulthood has a clear starting point|how nostalgia becomes a business model|whether shared pop culture is disappearing|the social cost of perpetual availability|the difference between delayed milestones and new values|who gets to define a generation` },
  { name: "History & futures", icon: "⌛", subjects: `a historical invention you take for granted|a message for your future self|a time capsule for your neighborhood|a day in a city a hundred years ago|the object that best represents today|why some inventions arrive too early|what future museums will say about us|whether history is driven by people or circumstances|how everyday objects preserve history|the future of the high street|who has the right to tell a community's history|whether progress is reversible|how societies should remember complicated heroes|the limits of predicting the future from the past|what we owe people whose names history forgot` },
  { name: "Design & cities", icon: "▦", subjects: `a door that is confusing to open|your ideal public park|the chair you could sit in all day|a sign that made you smile|a building you would turn into something else|whether cities need more quiet spaces|what makes a street feel welcoming|the hidden design of waiting rooms|why some objects age beautifully|whether cars should be guests in cities|who gets excluded by supposedly universal design|the politics of hostile architecture|whether a city should have a maximum size|balancing heritage with accessible housing|how to design for needs that are not visible` },
  { name: "Oddly specific", icon: "⚡", subjects: `the social life of a missing sock|why the second pancake is always better|the correct number of browser tabs|the tiny spoon everyone prefers|a dramatic review of your office printer|the etiquette of the last slice of pizza|why hotel corridors feel mysterious|the unspoken politics of a shared thermostat|whether a hot dog is a sandwich|why we wave at someone who cannot hear us|whether a replica of your childhood home is still home|the philosophy of saving the best bite for last|who owns the armrest on a plane|the ethics of returning a shopping cart|whether a playlist is a form of autobiography` },
];
export const topics: Topic[] = categories.flatMap(({name, subjects}) => subjects.split("|").map((subject, i) => ({id: `${name}-${i}`, category:name, subject, text: `${subject[0].toUpperCase()}${subject.slice(1)}`, difficulty: i < 5 ? "Easy" : i < 10 ? "Medium" : "Hard"})));
export const challenges = [
  { name: "Free speak", icon: "🎙", label: "Make it your own", instruction: "Take a position, tell a story, or follow your curiosity.", prefix: "Talk about" },
  { name: "Hot take", icon: "🌶️", label: "A little controversy", instruction: "Take a surprising position. Give two reasons and address one objection.", prefix: "Share your most unexpected take on" },
  { name: "One-minute pitch", icon: "💡", label: "Make us believe", instruction: "Hook us, name the problem, sell your idea, and finish with a clear ask.", prefix: "Pitch an idea inspired by" },
  { name: "Explain like I’m 5", icon: "🧸", label: "Keep it wonderfully simple", instruction: "Use an everyday comparison. Skip jargon and end with a simple example.", prefix: "Explain to a five-year-old" },
  { name: "Roast it", icon: "🔥", label: "All in good fun", instruction: "Find the absurd detail and exaggerate it. Keep the joke on the idea.", prefix: "Give a playful roast of" },
  { name: "Defend the worst take", icon: "🤹", label: "Play devil’s advocate", instruction: "Invent a ridiculous opinion and make the strongest playful case for it.", prefix: "Defend an intentionally terrible opinion about" },
  { name: "Tell a story", icon: "📖", label: "Take us somewhere", instruction: "Set the scene, introduce a complication, and land on a change or lesson.", prefix: "Tell a real or imagined story about" },
  { name: "Conspiracy corner", icon: "🛸", label: "Fiction, with a straight face", instruction: "Invent an obviously fictional, lighthearted conspiracy. No real-world accusations.", prefix: "Invent a delightfully silly conspiracy about" },
];
export function selectTopic(pool: Topic[], used: string[], random = Math.random): Topic | undefined {
  const unseen = pool.filter(t => !used.includes(t.id));
  const choices = unseen.length ? unseen : pool;
  return choices[Math.floor(random() * choices.length)];
}
